---
- name: Install Apache and Start/Stop It
  hosts: webserver
  become: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Apache (Apache2 package for Ubuntu)
      apt:
        name: apache2
        state: present
      become: yes

    - name: Start Apache
      service:
        name: apache2
        state: started
      become: yes

    - name: Stop Apache
      service:
        name: apache2
        state: stopped
      become: yes
